services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped

    volumes:
      - /mnt/ssd2:/srv
      - /mnt/ssd2/appdata/filebrowser/database:/database
      - /mnt/ssd2/appdata/filebrowser/config:/config

    networks:
      - proxy_net

  csv-converter-go:
    image: bkarowna/csv-converter-go:1.0.0
    container_name: csv-converter-go
    restart: unless-stopped

    ports:
      - "8088:8088"

    networks:
      - proxy_net

  csv-converter-python:
    image: bkarowna/csv-converter-python:1.1.1
    container_name: csv-converter-python
    restart: unless-stopped

    ports:
      - "8090:8090"

    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
