services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped

    volumes:
      - /mnt/ssd2:/ssd2
      - /mnt/ssd2/appdata/filebrowser/srv:/srv
      - /mnt/ssd2/appdata/filebrowser/database:/database
      - /mnt/ssd2/appdata/filebrowser/config:/config

    networks:
      - proxy_net

networks:
  proxy_net:
    external: true