services:
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxpm
    restart: unless-stopped

    ports:
      - "80:80"
      - "81:81"
      - "443:443"

    volumes:
      - /mnt/ssd2/appdata/nginxpm:/data
      - /mnt/ssd2/appdata/nginxpm/letsencrypt:/etc/letsencrypt

    networks:
      - proxy_net

  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    hostname: pihole

    environment:
      - TZ=Europe/London
      - WEBPASSWORD=changeme
      - DNSMASQ_LISTENING=all
      - WEB_PORT=8080

    volumes:
      - /mnt/ssd2/appdata/pihole/etc-pihole:/etc/pihole
      - /mnt/ssd2/appdata/pihole/etc-dnsmasq.d:/etc/dnsmasq.d

    network_mode: host

    restart: unless-stopped

networks:
  proxy_net:
    external: true